"""remove scoping from analysis_reports

Revision ID: 9c0efd60df39
Revises: d958a3c65acd
Create Date: 2025-08-17 14:08:15.489392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0efd60df39'
down_revision = 'd958a3c65acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('analysis_reports_laboratory_uid_fkey', 'analysis_reports', type_='foreignkey')
    op.drop_column('analysis_reports', 'laboratory_uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reports', sa.Column('laboratory_uid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('analysis_reports_laboratory_uid_fkey', 'analysis_reports', 'laboratory', ['laboratory_uid'], ['uid'])
    # ### end Alembic commands ###
