"""added user active laboratory

Revision ID: cf889b8db893
Revises: 322d323a4bfe
Create Date: 2025-07-22 23:17:21.748076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf889b8db893'
down_revision = '322d323a4bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_laboratory_uid', sa.String(), nullable=True))
    op.create_foreign_key(None, 'user', 'laboratory', ['active_laboratory_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'active_laboratory_uid')
    # ### end Alembic commands ###
