"""added lab-users table

Revision ID: 322d323a4bfe
Revises: d7f6bf2dbd29
Create Date: 2025-07-22 22:20:20.689131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322d323a4bfe'
down_revision = 'd7f6bf2dbd29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratory_user',
    sa.Column('laboratory_uid', sa.String(), nullable=True),
    sa.Column('user_uid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['laboratory_uid'], ['laboratory.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('user_uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laboratory_user')
    # ### end Alembic commands ###
