"""change lab instrument to maybe lab scoped

Revision ID: 6c605d7b8b84
Revises: db93f46f41c7
Create Date: 2025-08-17 18:31:04.992174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c605d7b8b84'
down_revision = 'db93f46f41c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laboratory_instrument', 'laboratory_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laboratory_instrument', 'laboratory_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
