"""lab users primar key

Revision ID: d958a3c65acd
Revises: cf889b8db893
Create Date: 2025-08-12 17:06:37.774498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd958a3c65acd'
down_revision = 'cf889b8db893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laboratory_user', 'laboratory_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laboratory_user', 'laboratory_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
