"""add extra metadata to auditlog

Revision ID: f5cc4ea0a9cb
Revises: 6c605d7b8b84
Create Date: 2025-08-24 12:48:29.815848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5cc4ea0a9cb'
down_revision = '6c605d7b8b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'extras')
    # ### end Alembic commands ###
