"""added billing extras

Revision ID: d9ba3ba7cecf
Revises: 0cc2d1826548
Create Date: 2025-10-12 15:45:17.267089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ba3ba7cecf'
down_revision = '0cc2d1826548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_request', sa.Column('is_billed', sa.Boolean(), nullable=True))
    op.add_column('analysis_request', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('laboratory_setting', sa.Column('process_billed_only', sa.Boolean(), nullable=True))
    op.add_column('laboratory_setting', sa.Column('min_payment_status', sa.String(), nullable=True))
    op.add_column('laboratory_setting', sa.Column('min_partial_perentage', sa.Float(), nullable=True))
    op.add_column('organization_setting', sa.Column('process_billed_only', sa.Boolean(), nullable=True))
    op.add_column('organization_setting', sa.Column('min_payment_status', sa.String(), nullable=True))
    op.add_column('organization_setting', sa.Column('min_partial_perentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_setting', 'min_partial_perentage')
    op.drop_column('organization_setting', 'min_payment_status')
    op.drop_column('organization_setting', 'process_billed_only')
    op.drop_column('laboratory_setting', 'min_partial_perentage')
    op.drop_column('laboratory_setting', 'min_payment_status')
    op.drop_column('laboratory_setting', 'process_billed_only')
    op.drop_column('analysis_request', 'is_locked')
    op.drop_column('analysis_request', 'is_billed')
    # ### end Alembic commands ###
