"""hipaa-compliance

Revision ID: 225f793a73ce
Revises: 325f9c7aaf07
Create Date: 2025-07-06 22:49:20.731473

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from felicity.utils.hipaa_fields import EncryptedPHIType, EncryptedPIIType

# revision identifiers, used by Alembic.
revision = '225f793a73ce'
down_revision = '325f9c7aaf07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_search_index',
                    sa.Column('patient_uid', sa.String(), nullable=False),
                    sa.Column('field_name', sa.String(), nullable=False),
                    sa.Column('year_hash', sa.String(), nullable=True),
                    sa.Column('month_hash', sa.String(), nullable=True),
                    sa.Column('day_hash', sa.String(), nullable=True),
                    sa.Column('date_hash', sa.String(), nullable=False),
                    sa.Column('age_range_hash', sa.String(), nullable=True),
                    sa.Column('uid', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by_uid', sa.String(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by_uid', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], ),
                    sa.ForeignKeyConstraint(['patient_uid'], ['patient.uid'], ),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], ),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_index('idx_date_age_range', 'date_search_index', ['field_name', 'age_range_hash'], unique=False)
    op.create_index('idx_date_full', 'date_search_index', ['field_name', 'date_hash'], unique=False)
    op.create_index('idx_date_month', 'date_search_index', ['field_name', 'month_hash'], unique=False)
    op.create_index('idx_date_year', 'date_search_index', ['field_name', 'year_hash'], unique=False)
    op.create_index(op.f('ix_date_search_index_age_range_hash'), 'date_search_index', ['age_range_hash'], unique=False)
    op.create_index(op.f('ix_date_search_index_date_hash'), 'date_search_index', ['date_hash'], unique=False)
    op.create_index(op.f('ix_date_search_index_day_hash'), 'date_search_index', ['day_hash'], unique=False)
    op.create_index(op.f('ix_date_search_index_month_hash'), 'date_search_index', ['month_hash'], unique=False)
    op.create_index(op.f('ix_date_search_index_uid'), 'date_search_index', ['uid'], unique=False)
    op.create_index(op.f('ix_date_search_index_year_hash'), 'date_search_index', ['year_hash'], unique=False)
    op.create_table('patient_search_index',
                    sa.Column('patient_uid', sa.String(), nullable=False),
                    sa.Column('field_name', sa.String(), nullable=False),
                    sa.Column('search_hash', sa.String(), nullable=False),
                    sa.Column('partial_hash_3', sa.String(), nullable=True),
                    sa.Column('partial_hash_4', sa.String(), nullable=True),
                    sa.Column('partial_hash_5', sa.String(), nullable=True),
                    sa.Column('phonetic_hash', sa.String(), nullable=True),
                    sa.Column('value_length', sa.String(), nullable=True),
                    sa.Column('uid', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by_uid', sa.String(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by_uid', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], ),
                    sa.ForeignKeyConstraint(['patient_uid'], ['patient.uid'], ),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], ),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_index('idx_patient_field_hash', 'patient_search_index', ['field_name', 'search_hash'], unique=False)
    op.create_index('idx_patient_partial_3', 'patient_search_index', ['field_name', 'partial_hash_3'], unique=False)
    op.create_index('idx_patient_partial_4', 'patient_search_index', ['field_name', 'partial_hash_4'], unique=False)
    op.create_index('idx_patient_partial_5', 'patient_search_index', ['field_name', 'partial_hash_5'], unique=False)
    op.create_index('idx_patient_phonetic', 'patient_search_index', ['field_name', 'phonetic_hash'], unique=False)
    op.create_index(op.f('ix_patient_search_index_partial_hash_3'), 'patient_search_index', ['partial_hash_3'],
                    unique=False)
    op.create_index(op.f('ix_patient_search_index_partial_hash_4'), 'patient_search_index', ['partial_hash_4'],
                    unique=False)
    op.create_index(op.f('ix_patient_search_index_partial_hash_5'), 'patient_search_index', ['partial_hash_5'],
                    unique=False)
    op.create_index(op.f('ix_patient_search_index_phonetic_hash'), 'patient_search_index', ['phonetic_hash'],
                    unique=False)
    op.create_index(op.f('ix_patient_search_index_search_hash'), 'patient_search_index', ['search_hash'], unique=False)
    op.create_index(op.f('ix_patient_search_index_uid'), 'patient_search_index', ['uid'], unique=False)
    op.create_table('phone_search_index',
                    sa.Column('patient_uid', sa.String(), nullable=False),
                    sa.Column('field_name', sa.String(), nullable=False),
                    sa.Column('normalized_hash', sa.String(), nullable=False),
                    sa.Column('last_four_hash', sa.String(), nullable=True),
                    sa.Column('area_code_hash', sa.String(), nullable=True),
                    sa.Column('uid', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by_uid', sa.String(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by_uid', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], ),
                    sa.ForeignKeyConstraint(['patient_uid'], ['patient.uid'], ),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], ),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_index('idx_phone_area_code', 'phone_search_index', ['field_name', 'area_code_hash'], unique=False)
    op.create_index('idx_phone_last_four', 'phone_search_index', ['field_name', 'last_four_hash'], unique=False)
    op.create_index('idx_phone_normalized', 'phone_search_index', ['field_name', 'normalized_hash'], unique=False)
    op.create_index(op.f('ix_phone_search_index_area_code_hash'), 'phone_search_index', ['area_code_hash'],
                    unique=False)
    op.create_index(op.f('ix_phone_search_index_last_four_hash'), 'phone_search_index', ['last_four_hash'],
                    unique=False)
    op.create_index(op.f('ix_phone_search_index_normalized_hash'), 'phone_search_index', ['normalized_hash'],
                    unique=False)
    op.create_index(op.f('ix_phone_search_index_uid'), 'phone_search_index', ['uid'], unique=False)
    op.alter_column('analysis_result', 'result',
                    existing_type=sa.TEXT(),
                    type_=EncryptedPHIType(length=1000),
                    existing_nullable=True)
    op.alter_column('clinical_data', 'symptoms_raw',
                    existing_type=sa.TEXT(),
                    type_=EncryptedPHIType(length=2000),
                    existing_nullable=True)
    op.alter_column('clinical_data', 'clinical_indication',
                    existing_type=sa.TEXT(),
                    type_=EncryptedPHIType(length=2000),
                    existing_nullable=True)
    op.alter_column('clinical_data', 'vitals',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=EncryptedPHIType(length=1000),
                    existing_nullable=True)
    op.alter_column('clinical_data', 'treatment_notes',
                    existing_type=sa.TEXT(),
                    type_=EncryptedPHIType(length=2000),
                    existing_nullable=True)
    op.alter_column('clinical_data', 'other_context',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=EncryptedPHIType(length=2000),
                    existing_nullable=True)
    op.alter_column('patient', 'date_of_birth',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=EncryptedPIIType(length=500),
                    existing_nullable=True)
    op.drop_index('ix_patient_identification_value', table_name='patient_identification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_patient_identification_value', 'patient_identification', ['value'], unique=False)
    op.alter_column('patient', 'date_of_birth',
                    existing_type=EncryptedPIIType(length=500),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('clinical_data', 'other_context',
                    existing_type=EncryptedPHIType(length=2000),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('clinical_data', 'treatment_notes',
                    existing_type=EncryptedPHIType(length=2000),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.alter_column('clinical_data', 'vitals',
                    existing_type=EncryptedPHIType(length=1000),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('clinical_data', 'clinical_indication',
                    existing_type=EncryptedPHIType(length=2000),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.alter_column('clinical_data', 'symptoms_raw',
                    existing_type=EncryptedPHIType(length=2000),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.alter_column('analysis_result', 'result',
                    existing_type=EncryptedPHIType(length=1000),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.drop_index(op.f('ix_phone_search_index_uid'), table_name='phone_search_index')
    op.drop_index(op.f('ix_phone_search_index_normalized_hash'), table_name='phone_search_index')
    op.drop_index(op.f('ix_phone_search_index_last_four_hash'), table_name='phone_search_index')
    op.drop_index(op.f('ix_phone_search_index_area_code_hash'), table_name='phone_search_index')
    op.drop_index('idx_phone_normalized', table_name='phone_search_index')
    op.drop_index('idx_phone_last_four', table_name='phone_search_index')
    op.drop_index('idx_phone_area_code', table_name='phone_search_index')
    op.drop_table('phone_search_index')
    op.drop_index(op.f('ix_patient_search_index_uid'), table_name='patient_search_index')
    op.drop_index(op.f('ix_patient_search_index_search_hash'), table_name='patient_search_index')
    op.drop_index(op.f('ix_patient_search_index_phonetic_hash'), table_name='patient_search_index')
    op.drop_index(op.f('ix_patient_search_index_partial_hash_5'), table_name='patient_search_index')
    op.drop_index(op.f('ix_patient_search_index_partial_hash_4'), table_name='patient_search_index')
    op.drop_index(op.f('ix_patient_search_index_partial_hash_3'), table_name='patient_search_index')
    op.drop_index('idx_patient_phonetic', table_name='patient_search_index')
    op.drop_index('idx_patient_partial_5', table_name='patient_search_index')
    op.drop_index('idx_patient_partial_4', table_name='patient_search_index')
    op.drop_index('idx_patient_partial_3', table_name='patient_search_index')
    op.drop_index('idx_patient_field_hash', table_name='patient_search_index')
    op.drop_table('patient_search_index')
    op.drop_index(op.f('ix_date_search_index_year_hash'), table_name='date_search_index')
    op.drop_index(op.f('ix_date_search_index_uid'), table_name='date_search_index')
    op.drop_index(op.f('ix_date_search_index_month_hash'), table_name='date_search_index')
    op.drop_index(op.f('ix_date_search_index_day_hash'), table_name='date_search_index')
    op.drop_index(op.f('ix_date_search_index_date_hash'), table_name='date_search_index')
    op.drop_index(op.f('ix_date_search_index_age_range_hash'), table_name='date_search_index')
    op.drop_index('idx_date_year', table_name='date_search_index')
    op.drop_index('idx_date_month', table_name='date_search_index')
    op.drop_index('idx_date_full', table_name='date_search_index')
    op.drop_index('idx_date_age_range', table_name='date_search_index')
    op.drop_table('date_search_index')
    # ### end Alembic commands ###
