"""remove scoping from client

Revision ID: db93f46f41c7
Revises: 59e64f873eea
Create Date: 2025-08-17 15:05:19.814524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db93f46f41c7'
down_revision = '59e64f873eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_laboratory_uid', table_name='client')
    op.drop_constraint('client_laboratory_uid_fkey', 'client', type_='foreignkey')
    op.drop_column('client', 'laboratory_uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('laboratory_uid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('client_laboratory_uid_fkey', 'client', 'laboratory', ['laboratory_uid'], ['uid'])
    op.create_index('ix_client_laboratory_uid', 'client', ['laboratory_uid'], unique=False)
    # ### end Alembic commands ###
