"""add driver_mapping to instruments

Revision ID: add_driver_mapping
Revises: 26d2498c0da9
Create Date: 2025-10-27 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_driver_mapping'
down_revision = '26d2498c0da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument', sa.Column('driver_mapping', sa.JSON(), nullable=True))
    op.add_column('laboratory_instrument', sa.Column('driver_mapping', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laboratory_instrument', 'driver_mapping')
    op.drop_column('instrument', 'driver_mapping')
    # ### end Alembic commands ###
